### ISSUE TITLE
Feature Request: GitHub Action Secrets

### ISSUE THREAD

**Issue by onlydole** [operatehappy/terraform-github-repository#18]
Being able to set secrets for GitHub Actions would be a helpful feature to set from within this module. 

Currently this has to be set as an "external" resource like so:

```
resource "github_actions_secret" "ssh_key" {
  repository      = REPO_NAME
  secret_name     = "SSH_PRIVATE_KEY"
  plaintext_value = VERY_SECRET_KEY
}
```

**Comment by ksatirli** [comment]
I've thought about this and do not think supporting GHA Secrets via this Module makes sense, due to the nature of the variable's `plaintext_value` and how it relates to Terraform State.

Rather than maneuver it into a Terraform project and pollute (possibly large) state files, I'll document an approach that uses outputs from this Module and creates GHA Secrets in a separate TF project.
